#!/usr/bin/env python3
"""
Live LXMF receiver — uses real RNS + LXMF on this machine to act as a
test peer for the mobile app. Eliminates Sideband as a variable when
debugging "outbound from app doesn't reach the recipient."

Usage:
    pip install rns lxmf
    python tools/test_lxmf_receiver.py

What it does:
    1) Initializes RNS using your existing config under ~/.reticulum
       (or creates a default one). All TCP / RNode interfaces in that
       config become available.
    2) Generates (or loads) a fresh test identity for THIS receiver,
       stored in ~/.reticulum-mobile-app-test-identity.
    3) Stands up an LXMRouter delivery destination
       ("Mobile App Test Receiver"), announces every 5 minutes.
    4) Prints its destination hash so you can copy it into the app's
       Nodes tab as a manual entry, OR wait for the announce to
       propagate naturally.
    5) On every received LXMF message, logs source hash, content, and
       whether RNS auto-emitted a delivery proof back to the sender.

So the flow is:
    [your phone running the app] --TCP/BLE--> [some rnsd] --network-->
        [this rnsd] --> [this script]

If the app's outbound message reaches this script with the right
plaintext, the bug is Sideband-specific (config, ratchet, etc.). If
this script never sees the message, the bug is in our send path or in
the network between your transport and this PC.

Stop with Ctrl-C.
"""
import os
import sys
import time

os.environ.setdefault("RNS_LOG_DEST", "stderr")

# Windows-safe atomic rename. Upstream RNS persists ratchets via an
# atomic "write to .out, rename to final" pattern that races on
# Windows in two ways:
#   - PermissionError when the destination still has a brief OS lock
#   - FileNotFoundError when another concurrent ratchet update already
#     consumed the .out file
# Neither matters for the test receiver — ratchets aren't load-bearing
# for "did we receive the message and verify the signature." Ignoring
# the race is functionally identical to RNS retrying on the next
# announce that triggers a ratchet update.
# Capture the originals BEFORE patching, otherwise the wrapper recurses
# into itself (we just shadowed os.replace).
_orig_replace = os.replace
def _safe_rename(src, dst):
    try:
        _orig_replace(src, dst)
    except (FileNotFoundError, PermissionError):
        pass
os.rename = _safe_rename
os.replace = _safe_rename

try:
    import RNS
    import LXMF
except ImportError:
    print("Missing dependency. Install with:", file=sys.stderr)
    print("    pip install rns lxmf", file=sys.stderr)
    sys.exit(2)

DISPLAY_NAME = "Mobile App Test Receiver"
IDENTITY_PATH = os.path.expanduser("~/.reticulum-mobile-app-test-identity")
STORAGE_PATH = os.path.expanduser("~/.reticulum-mobile-app-test-receiver")
CONFIG_DIR   = os.path.expanduser("~/.reticulum-mobile-app-test-config")

# TCP transport this receiver should attach to. Override with env var
# TEST_RECEIVER_TCP="host:port" if you want to reach the app over a
# different rnsd than MichMesh.
DEFAULT_TCP = "RNS.MichMesh.net:7822"
TCP_TARGET = os.environ.get("TEST_RECEIVER_TCP", DEFAULT_TCP)

CONFIG_TEMPLATE = """\
# Auto-generated by tools/test_lxmf_receiver.py
# Isolated from ~/.reticulum/config so it doesn't pollute production.
[reticulum]
  enable_transport = False
  share_instance = No
  shared_instance_port = 37428
  instance_control_port = 37429
  panic_on_interface_error = No

[logging]
  loglevel = 4

[interfaces]

  [[Test Receiver TCP]]
    type = TCPClientInterface
    interface_enabled = true
    target_host = {host}
    target_port = {port}
    name = test_receiver_tcp
"""

ANSI_OK = "\033[32m"
ANSI_INFO = "\033[36m"
ANSI_ERR = "\033[31m"
ANSI_RESET = "\033[0m"

def log(tag, msg, color=ANSI_INFO):
    ts = time.strftime("%H:%M:%S")
    print(f"{color}[{ts} {tag}]{ANSI_RESET} {msg}", flush=True)

def main():
    # Load or create the test identity. Using a stable file means the
    # destination hash is the same across runs, so the app's contact row
    # for this receiver doesn't churn.
    if os.path.exists(IDENTITY_PATH):
        identity = RNS.Identity.from_file(IDENTITY_PATH)
        log("init", f"loaded existing identity from {IDENTITY_PATH}", ANSI_OK)
    else:
        identity = RNS.Identity()
        identity.to_file(IDENTITY_PATH)
        log("init", f"created new identity at {IDENTITY_PATH}", ANSI_OK)

    # Write isolated config (idempotent) and init RNS against it.
    os.makedirs(CONFIG_DIR, exist_ok=True)
    config_path = os.path.join(CONFIG_DIR, "config")
    if not os.path.exists(config_path):
        if ":" in TCP_TARGET:
            host, port = TCP_TARGET.rsplit(":", 1)
        else:
            host, port = TCP_TARGET, "7822"
        with open(config_path, "w") as f:
            f.write(CONFIG_TEMPLATE.format(host=host, port=port))
        log("init", f"wrote test config to {config_path} (TCP: {host}:{port})", ANSI_OK)
    else:
        log("init", f"using existing config at {config_path}", ANSI_OK)

    # loglevel=7 (Debug) — tells us when announces arrive, when DATA is
    # routed to our destination, and any decrypt/sig failures. Without
    # this RNS is silent and we can't tell whether the rnsd is forwarding
    # our destination's traffic at all.
    rns = RNS.Reticulum(configdir=CONFIG_DIR, loglevel=7)

    os.makedirs(STORAGE_PATH, exist_ok=True)
    router = LXMF.LXMRouter(identity=identity, storagepath=STORAGE_PATH)

    delivery_dest = router.register_delivery_identity(
        identity, display_name=DISPLAY_NAME
    )

    def message_received(message):
        src = RNS.prettyhexrep(message.source_hash) if message.source_hash else "???"
        try:
            content = message.content_as_string()
        except Exception:
            content = repr(message.content)
        sig = "OK" if message.signature_validated else "INVALID"
        log(
            "RX",
            f"from={src}  sig={sig}  content={content!r}",
            ANSI_OK if message.signature_validated else ANSI_ERR,
        )
        # LXMRouter automatically emits the delivery proof; nothing to do.

    router.register_delivery_callback(message_received)

    log("dest", f"display_name={DISPLAY_NAME!r}", ANSI_OK)
    log("dest", f"destHash={RNS.prettyhexrep(delivery_dest.hash)}", ANSI_OK)
    log("dest", f"identityHash={RNS.prettyhexrep(identity.hash)}", ANSI_OK)
    log("dest", f"announcing every ~5 min; first announce in 2s", ANSI_OK)

    # Announce loop.
    next_announce = time.time() + 2
    try:
        while True:
            now = time.time()
            if now >= next_announce:
                delivery_dest.announce()
                log("tx", "announce sent", ANSI_OK)
                next_announce = now + 300  # 5 min
            time.sleep(0.5)
    except KeyboardInterrupt:
        log("exit", "stopping (Ctrl-C)", ANSI_OK)

if __name__ == "__main__":
    main()
