#!/usr/bin/env python3
"""
Local RNS transport node for end-to-end testing.

Stands up a Reticulum instance with `enable_transport = True` and a
TCPServerInterface, so two TCP clients (the mobile app + the Python
test receiver) can connect and have DATA/Link traffic forwarded
between them. Eliminates the public-rnsd filtering quirks that
prevented the controlled-receiver test from completing end-to-end.

Usage:
    python tools/test_transport_node.py [--port 7822]

Then:
    # On host: forward phone's localhost:7822 to host
    adb reverse tcp:7822 tcp:7822
    # In app Settings: TCP host=127.0.0.1, port=7822
    # Receiver: TEST_RECEIVER_TCP=127.0.0.1:7822 python tools/test_lxmf_receiver.py
    #   (delete ~/.reticulum-mobile-app-test-config first to regen the config)

The transport runs in the foreground; logs go to stderr. Ctrl-C to stop.
Stops if it cannot bind the port.
"""
import argparse
import os
import sys
import time

os.environ.setdefault("RNS_LOG_DEST", "stderr")

CONFIG_DIR = os.path.expanduser("~/.reticulum-mobile-app-test-transport")
CONFIG_TEMPLATE = """\
# Auto-generated by tools/test_transport_node.py
[reticulum]
  enable_transport = True
  share_instance = No
  shared_instance_port = 37448
  instance_control_port = 37449
  panic_on_interface_error = No

[logging]
  loglevel = 5

[interfaces]

  [[Local Test Transport TCP]]
    type = TCPServerInterface
    interface_enabled = True
    listen_ip = 0.0.0.0
    listen_port = {port}
    name = local_test_transport
"""

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--port", default=7822, type=int)
    args = p.parse_args()

    os.makedirs(CONFIG_DIR, exist_ok=True)
    config_path = os.path.join(CONFIG_DIR, "config")
    with open(config_path, "w") as f:
        f.write(CONFIG_TEMPLATE.format(port=args.port))
    print(f"== wrote config to {config_path}", file=sys.stderr, flush=True)

    try:
        import RNS
    except ImportError:
        print("Missing dependency. pip install rns", file=sys.stderr)
        sys.exit(2)

    rns = RNS.Reticulum(configdir=CONFIG_DIR, loglevel=5)
    print(f"== transport node up on TCP {args.port} (transport=True)", file=sys.stderr, flush=True)
    print(f"== identity hash: {RNS.prettyhexrep(RNS.Transport.identity.hash) if hasattr(RNS.Transport, 'identity') else '(transport identity unavailable)'}",
          file=sys.stderr, flush=True)
    try:
        while True:
            time.sleep(60)
    except KeyboardInterrupt:
        print("== shutting down", file=sys.stderr, flush=True)

if __name__ == "__main__":
    main()
